/**
 * Product List
 * 
 * This file contains the product data used for displaying thrifted items.
 * Each product is an object containing details such as name, image, description, 
 * brand, category, price, condition, size, material, era, and uniqueness.
 */

const products = [
  {
    _id: '1',
    name: 'The Cranberries T-Shirt',
    image: '/images/theCranberries.JPG',
    description: 'A stylish red t-shirt featuring The Cranberries artwork. Comfortable and unique.',
    brand: 'Thrift Daddy',
    category: 'T-Shirts',
    price: 24.99,
    condition: 'Good',
    size: 'Medium',
    material: '100% Cotton',
    era: '1990s', // The era or style of the item
    isUnique: true, // Indicates if the item is one-of-a-kind
  },
  {
    _id: '2',
    name: 'The Cure T-Shirt',
    image: '/images/theCure.JPG',
    description: 'Vintage-inspired black t-shirt with The Cure design. Perfect for fans and collectors.',
    brand: 'Thrift Daddy',
    category: 'T-Shirts',
    price: 29.99,
    condition: 'Excellent',
    size: 'Large',
    material: 'Polyester Blend',
    era: '1980s',
    isUnique: true,
  },
  {
    _id: '3',
    name: 'Star Wars Tie-Dye T-Shirt',
    image: '/images/starWars.JPG',
    description: 'A colorful tie-dye t-shirt featuring iconic Star Wars characters. Perfect for casual wear.',
    brand: 'Thrift Daddy',
    category: 'T-Shirts',
    price: 34.99,
    condition: 'Very Good',
    size: 'Large',
    material: '100% Cotton',
    era: '2000s',
    isUnique: true,
  },
  {
    _id: '4',
    name: 'Grateful Dead Tie-Dye T-Shirt',
    image: '/images/gratefulDead.JPG',
    description: 'Bold tie-dye t-shirt with Grateful Dead artwork. A must-have for music lovers.',
    brand: 'Thrift Daddy',
    category: 'T-Shirts',
    price: 39.99,
    condition: 'Good',
    size: 'XL',
    material: 'Cotton Blend',
    era: '1990s',
    isUnique: true,
  },
  {
    _id: '5',
    name: 'Eminem T-Shirt',
    image: '/images/eminem.JPG',
    description: 'A vintage Eminem t-shirt with bold graphics. Perfect for fans and collectors.',
    brand: 'Thrift Daddy',
    category: 'T-Shirts',
    price: 22.99,
    condition: 'Good',
    size: 'Medium',
    material: '100% Cotton',
    era: '2000s',
    isUnique: true,
  },
  {
    _id: '6',
    name: 'Evangelion T-Shirt',
    image: '/images/evangelion.JPG',
    description: 'A unique Evangelion t-shirt for anime lovers. A must-have for collectors.',
    brand: 'Thrift Daddy',
    category: 'T-Shirts',
    price: 35.99,
    condition: 'Excellent',
    size: 'Large',
    material: '100% Cotton',
    era: '1990s',
    isUnique: true,
  },
  {
    _id: '7',
    name: 'Harley Davidson T-Shirt',
    image: '/images/harleyDavidson.JPG',
    description: 'Vintage Harley Davidson t-shirt with bold graphics. A perfect find for bike enthusiasts.',
    brand: 'Thrift Daddy',
    category: 'T-Shirts',
    price: 45.99,
    condition: 'Very Good',
    size: 'XL',
    material: '100% Cotton',
    era: '1980s',
    isUnique: true,
  },
  {
    _id: '8',
    name: 'Naruto T-Shirt',
    image: '/images/naruto.JPG',
    description: 'A unique Naruto t-shirt for anime fans. A bold and stylish addition to any collection.',
    brand: 'Thrift Daddy',
    category: 'T-Shirts',
    price: 28.99,
    condition: 'Good',
    size: 'Medium',
    material: 'Cotton Blend',
    era: '2000s',
    isUnique: true,
  },
];

export default products;
